// Package main 提供 mworm 字段常量生成器
// 用法:
//
//	单文件: go run ./cmd/fieldgen -src=path/to/model.go
//	目录:   go run ./cmd/fieldgen -dir=path/to/models
//	递归:   go run ./cmd/fieldgen -dir=path/to/models -r
//
// 通过 go generate: //go:generate go run github.com/ccxdd/mworm/cmd/fieldgen -src=$GOFILE
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// 字段信息
type FieldInfo struct {
	GoName   string // 结构体字段名
	JsonName string // JSON 标签值
}

// 结构体信息
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

// 模板数据
type TemplateData struct {
	Package string
	Structs []StructInfo
}

// 生成模板
const fieldsTmpl = `// Code generated by mworm/cmd/fieldgen. DO NOT EDIT.
package {{.Package}}

{{range .Structs}}
// {{.Name}}F 提供 {{.Name}} 的类型安全字段名常量
var {{.Name}}F = struct {
{{- range .Fields}}
	{{.GoName}} string
{{- end}}
}{
{{- range .Fields}}
	{{.GoName}}: "{{.JsonName}}",
{{- end}}
}
{{end}}
`

func main() {
	srcFile := flag.String("src", "", "源文件路径")
	srcDir := flag.String("dir", "", "源目录路径（批量处理）")
	recursive := flag.Bool("r", false, "是否递归处理子目录")
	flag.Parse()

	if *srcFile == "" && *srcDir == "" {
		fmt.Println("用法:")
		fmt.Println("  单文件: fieldgen -src=path/to/model.go")
		fmt.Println("  目录:   fieldgen -dir=path/to/models")
		fmt.Println("  递归:   fieldgen -dir=path/to/models -r")
		os.Exit(1)
	}

	if *srcDir != "" {
		// 目录模式
		processDir(*srcDir, *recursive)
	} else {
		// 单文件模式
		if err := processFile(*srcFile); err != nil {
			fmt.Printf("处理失败: %v\n", err)
			os.Exit(1)
		}
	}
}

// processDir 处理目录下的所有 Go 文件
func processDir(dir string, recursive bool) {
	var count int
	walkFn := func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// 跳过目录本身
		if info.IsDir() {
			if !recursive && path != dir {
				return filepath.SkipDir
			}
			return nil
		}

		// 只处理 .go 文件，跳过 _test.go 和已生成的 _fields.go
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, "_fields.go") {
			return nil
		}

		if err := processFile(path); err != nil {
			fmt.Printf("跳过 %s: %v\n", path, err)
		} else {
			count++
		}
		return nil
	}

	if err := filepath.Walk(dir, walkFn); err != nil {
		fmt.Printf("遍历目录失败: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("共处理 %d 个文件\n", count)
}

// processFile 处理单个文件
func processFile(srcFile string) error {
	// 解析源文件
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, srcFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("解析文件失败: %v", err)
	}

	// 第一遍：收集实现了 TableName() 方法或带有 //+fieldgen 注释的结构体名称
	ormStructs := make(map[string]bool)
	for _, decl := range node.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Recv != nil && d.Name.Name == "TableName" {
				// 获取接收者类型名
				if len(d.Recv.List) > 0 {
					switch t := d.Recv.List[0].Type.(type) {
					case *ast.Ident:
						ormStructs[t.Name] = true
					case *ast.StarExpr:
						if ident, ok := t.X.(*ast.Ident); ok {
							ormStructs[ident.Name] = true
						}
					}
				}
			}
		case *ast.GenDecl:
			if d.Tok == token.TYPE && d.Doc != nil {
				for _, comment := range d.Doc.List {
					if strings.Contains(comment.Text, "+fieldgen") {
						for _, spec := range d.Specs {
							if typeSpec, ok := spec.(*ast.TypeSpec); ok {
								ormStructs[typeSpec.Name.Name] = true
							}
						}
					}
				}
			}
		}
	}

	// 第二遍：收集所有结构体定义（用于嵌套查找）
	allStructs := make(map[string]*ast.StructType)
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if structType, ok := typeSpec.Type.(*ast.StructType); ok {
				allStructs[typeSpec.Name.Name] = structType
			}
		}
	}

	// 第三遍：收集结构体信息（只处理实现了 ORMInterface 的）
	var structs []StructInfo
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			// 检查是否实现了 ORMInterface
			if !ormStructs[typeSpec.Name.Name] {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			fields := extractFields(structType, allStructs, make(map[string]bool))

			if len(fields) > 0 {
				structs = append(structs, StructInfo{
					Name:   typeSpec.Name.Name,
					Fields: fields,
				})
			}
		}
	}

	if len(structs) == 0 {
		return fmt.Errorf("未找到实现 ORMInterface 的结构体")
	}

	// 对结构体按名称排序，确保生成顺序稳定
	sort.Slice(structs, func(i, j int) bool {
		return structs[i].Name < structs[j].Name
	})

	// 生成代码
	data := TemplateData{
		Package: node.Name.Name,
		Structs: structs,
	}

	tmpl, err := template.New("fields").Parse(fieldsTmpl)
	if err != nil {
		return fmt.Errorf("模板解析失败: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("模板执行失败: %v", err)
	}

	// 格式化代码
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("代码格式化失败: %v", err)
	}

	// 写入文件
	dir := filepath.Dir(srcFile)
	base := filepath.Base(srcFile)
	ext := filepath.Ext(base)
	outFile := filepath.Join(dir, strings.TrimSuffix(base, ext)+"_fields.go")

	if err := os.WriteFile(outFile, formatted, 0644); err != nil {
		return fmt.Errorf("写入文件失败: %v", err)
	}

	fmt.Printf("已生成: %s\n", outFile)
	return nil
}

// extractTag 从标签字符串中提取指定键的值
func extractTag(tag, key string) string {
	// 查找 key:"value" 模式
	search := key + `:"`
	idx := strings.Index(tag, search)
	if idx == -1 {
		return ""
	}
	start := idx + len(search)
	end := strings.Index(tag[start:], `"`)
	if end == -1 {
		return ""
	}
	return tag[start : start+end]
}

// extractFields 从结构体中提取字段信息，支持嵌套结构体
func extractFields(structType *ast.StructType, allStructs map[string]*ast.StructType, visited map[string]bool) []FieldInfo {
	var fields []FieldInfo

	for _, field := range structType.Fields.List {
		// 嵌套结构体（匿名字段）
		if len(field.Names) == 0 {
			var embeddedName string
			switch t := field.Type.(type) {
			case *ast.Ident:
				embeddedName = t.Name
			case *ast.StarExpr:
				if ident, ok := t.X.(*ast.Ident); ok {
					embeddedName = ident.Name
				}
			}

			// 防止循环引用
			if embeddedName != "" && !visited[embeddedName] {
				if embeddedStruct, ok := allStructs[embeddedName]; ok {
					visited[embeddedName] = true
					embeddedFields := extractFields(embeddedStruct, allStructs, visited)
					fields = append(fields, embeddedFields...)
				}
			}
			continue
		}

		// 普通字段
		if field.Tag == nil {
			continue
		}

		tagValue := strings.Trim(field.Tag.Value, "`")
		jsonTag := extractTag(tagValue, "json")
		if jsonTag == "" || jsonTag == "-" {
			continue
		}

		// 移除 omitempty 等选项
		jsonName := strings.Split(jsonTag, ",")[0]
		if jsonName == "" {
			continue
		}

		fields = append(fields, FieldInfo{
			GoName:   field.Names[0].Name,
			JsonName: jsonName,
		})
	}

	return fields
}
